DROP TABLE IF EXISTS TBL_SUBSCRIBER;

CREATE TABLE TBL_SUBSCRIBER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  surname VARCHAR(250) NOT NULL,
  birthYear INT NOT NULL,
  gender VARCHAR(120) NULL,
  age INT NOT NULL,
  description VARCHAR(250) NOT NULL
);